# Generated by Django 5.0 on 2024-04-09 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='after_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('test_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.test')),
            ],
        ),
    ]
